apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.beta.openshift.io/serving-cert-secret-name: sso-service
  labels:
    application: sso
    component: server
    rhsso: 7.5.3.GA
  name: secure-sso
  namespace: sso-reencrypt
spec:
  type: ClusterIP
  ports:
  - port: 8443
  selector:
    app: sso
